CREATE TABLE PRODUCT (
    PRODUCT_ID int NOT NULL AUTO_INCREMENT,
    NAME varchar(255) NOT NULL,
    PRICE float,
    CATEGORY_ID int REFERENCES CATEGORY(CATEGORY_ID),
    PRIMARY KEY (PRODUCT_ID)
);

CREATE TABLE CATEGORY (
	CATEGORY_ID int NOT NULL AUTO_INCREMENT,
	NAME varchar(255) NOT NULL,
	PRIMARY KEY (CATEGORY_ID)
);

INSERT INTO CATEGORY (NAME) VALUES('Desktop'); --1
INSERT INTO CATEGORY (NAME) VALUES('Laptop'); --2
INSERT INTO CATEGORY (NAME) VALUES('Tablet'); --3
INSERT INTO CATEGORY (NAME) VALUES('Mobile'); --4

INSERT INTO PRODUCT (NAME, PRICE, CATEGORY_ID) VALUES ('IBM', 1000, 1);
INSERT INTO PRODUCT (NAME, PRICE, CATEGORY_ID) VALUES ('MS', 2000, 1);
INSERT INTO PRODUCT (NAME, PRICE, CATEGORY_ID) VALUES ('ASUS', 900, 1);
INSERT INTO PRODUCT (NAME, PRICE, CATEGORY_ID) VALUES ('LEGEND', 1500, 1);
INSERT INTO PRODUCT (NAME, PRICE, CATEGORY_ID) VALUES ('SONY', 1600, 1);


INSERT INTO PRODUCT (NAME, PRICE, CATEGORY_ID) VALUES ('IBM', 1500, 2);
INSERT INTO PRODUCT (NAME, PRICE, CATEGORY_ID) VALUES ('MS', 2600, 2);
INSERT INTO PRODUCT (NAME, PRICE, CATEGORY_ID) VALUES ('ASUS', 1900, 2);
INSERT INTO PRODUCT (NAME, PRICE, CATEGORY_ID) VALUES ('LEGEND', 1800, 2);
INSERT INTO PRODUCT (NAME, PRICE, CATEGORY_ID) VALUES ('SONY', 1700, 2);

INSERT INTO PRODUCT (NAME, PRICE, CATEGORY_ID) VALUES ('IBM', 1100, 3);
INSERT INTO PRODUCT (NAME, PRICE, CATEGORY_ID) VALUES ('MS', 600, 3);
INSERT INTO PRODUCT (NAME, PRICE, CATEGORY_ID) VALUES ('ASUS', 1090, 3);
INSERT INTO PRODUCT (NAME, PRICE, CATEGORY_ID) VALUES ('LEGEND', 800, 3);
INSERT INTO PRODUCT (NAME, PRICE, CATEGORY_ID) VALUES ('SONY', 700, 3);

INSERT INTO PRODUCT (NAME, PRICE, CATEGORY_ID) VALUES ('IBM', 1800, 4);
INSERT INTO PRODUCT (NAME, PRICE, CATEGORY_ID) VALUES ('MS', 1600, 4);
INSERT INTO PRODUCT (NAME, PRICE, CATEGORY_ID) VALUES ('ASUS', 1390, 4);
INSERT INTO PRODUCT (NAME, PRICE, CATEGORY_ID) VALUES ('LEGEND', 1100, 4);
INSERT INTO PRODUCT (NAME, PRICE, CATEGORY_ID) VALUES ('SONY', 600, 4);