CREATE TABLE PRODUCT (
    PRODUCT_ID int NOT NULL AUTO_INCREMENT,
    NAME varchar(255) NOT NULL,
    PRICE float,
    CATEGORY_ID int REFERENCES CATEGORY(CATEGORY_ID),
    PRIMARY KEY (PRODUCT_ID)
);

CREATE TABLE CATEGORY (
	CATEGORY_ID int NOT NULL AUTO_INCREMENT,
	NAME varchar(255) NOT NULL,
	PRIMARY KEY (PRODUCT_ID)
);